### ISSUE TITLE
forge_authorization

### ISSUE THREAD

**Issue by cdenneen** [puppetlabs/puppetlabs_spec_helper#345]
What is the best way to handle this for `.fixtures.yml`?

https://forge.puppet.com/about/premium

Looks like I can do it like this but obviously storing this into git might not be the best solution. Any other suggestions here?

```yaml
defaults:
  forge_modules:
    flags: "--module_repository=https://company.jfrog.io/artifactory/api/puppet/puppetrepo/ --authorization_token='Bearer MYTOKENHERE'"
```

Is there any other option to do this? In the link above it suggests that by updating `puppet.conf`, essentially running `puppet config set forge_authorization 'Bearer MYTOKENHERE` will work with `puppetlabs_spec_helper`. Is that the best solution then?

I just want to document the official recommendation of how to integrate `puppetlabs_spec_helper` with using Authorization.
